import { Gauge, Microscope, Search } from "lucide-react";

export function Diagnostics() {
  return (
    <div className="relative flex-1 overflow-y-auto px-8 pt-6 pb-16">
      <div className="mx-auto flex max-w-6xl flex-col gap-8">
        <div className="flex flex-col items-start gap-3 pt-2">
          <span className="font-mono text-[11px] tracking-[0.35em] text-violet-glow uppercase">
            Diagnostics
          </span>
          <h1 className="text-[28px] leading-tight font-semibold tracking-tight text-text">
            Root-cause investigations from the Diagnostic agent
          </h1>
          <p className="max-w-2xl text-[13px] text-text-dim">
            Per-engine and fleet-wide degradation hypotheses generated by the
            Diagnostic agent — ranked by sensor contribution, fleet deviation,
            and rate-of-decline. Click an engine to inspect its full sensor
            decomposition.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-3 md:grid-cols-3">
          <StatCard
            label="Open diagnoses"
            value="14"
            sub="awaiting acknowledgment"
            icon={Search}
          />
          <StatCard
            label="Top fault mode"
            value="HPC"
            sub="High-pressure compressor degradation"
            icon={Gauge}
          />
          <StatCard
            label="Avg confidence"
            value="0.87"
            sub="across active investigations"
            icon={Microscope}
          />
        </div>

        <div className="lift relative overflow-hidden rounded-xl border border-border bg-surface/70 p-8 backdrop-blur-sm">
          <div className="flex items-start gap-4">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-md border border-violet/30 bg-violet/10">
              <Gauge className="h-5 w-5 text-violet-glow" />
            </div>
            <div className="flex flex-col gap-2">
              <h2 className="text-[16px] font-semibold tracking-tight text-text">
                Diagnostic console coming soon
              </h2>
              <p className="max-w-xl text-[13px] leading-relaxed text-text-dim">
                Aggregate diagnostic view is in development. For per-engine root
                cause analysis today, open any engine from the Fleet view to see
                its sensor decomposition, degradation curve, and Diagnostic
                agent narrative.
              </p>
              <ul className="mt-2 flex flex-col gap-1.5 text-[12px] text-text-dim">
                <Item>Fleet-wide fault-mode classifier output</Item>
                <Item>Sensor contribution rankings by engine cohort</Item>
                <Item>Confidence intervals on degradation slopes</Item>
                <Item>Side-by-side comparison of flagged engines</Item>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function StatCard({
  label,
  value,
  sub,
  icon: Icon,
}: {
  label: string;
  value: string;
  sub: string;
  icon: React.ComponentType<{ className?: string }>;
}) {
  return (
    <div className="lift relative overflow-hidden rounded-xl border border-border bg-surface/70 p-4 backdrop-blur-sm">
      <div className="flex items-center justify-between">
        <span className="text-[11px] font-medium tracking-wider text-text-faint uppercase">
          {label}
        </span>
        <Icon className="h-3.5 w-3.5 text-violet-glow" />
      </div>
      <div className="mt-2 font-mono text-[26px] font-semibold tracking-tight text-text">
        {value}
      </div>
      <span className="mt-1 text-[11px] text-text-faint">{sub}</span>
    </div>
  );
}

function Item({ children }: { children: React.ReactNode }) {
  return (
    <li className="flex items-center gap-2">
      <span className="h-1 w-1 rounded-full bg-violet-glow" />
      <span>{children}</span>
    </li>
  );
}
