import { useMemo } from "react";
import { Link } from "react-router-dom";
import {
  AlertTriangle,
  ArrowUpRight,
  CheckCircle2,
  Eye,
  FileDown,
  Wrench,
} from "lucide-react";
import { SeverityBadge } from "../components/SeverityBadge";
import { makeMockFleet, makeMockRecommendations } from "../lib/mock";
import { cn } from "../lib/cn";
import type { Recommendation, Severity } from "../lib/types";

export function Recommendations() {
  const recs = useMemo(() => makeMockRecommendations(makeMockFleet(100)), []);

  const grouped = useMemo(() => {
    const critical = recs.filter((r) => r.severity === "critical");
    const warning = recs.filter((r) => r.severity === "warning");
    const healthy = recs.filter((r) => r.severity === "healthy");
    const bySeverity = (a: Recommendation, b: Recommendation) =>
      a.predicted_rul - b.predicted_rul;
    return {
      critical: critical.sort(bySeverity),
      warning: warning.sort(bySeverity),
      healthy: healthy.sort(bySeverity),
    };
  }, [recs]);

  return (
    <div className="relative flex-1 overflow-y-auto px-8 pt-6 pb-16">
      <div className="mx-auto flex max-w-6xl flex-col gap-8">
        <Hero counts={{
          critical: grouped.critical.length,
          warning: grouped.warning.length,
          healthy: grouped.healthy.length,
        }} />

        <Section
          tone="critical"
          title="Critical"
          subtitle="Immediate action required"
          icon={AlertTriangle}
          recs={grouped.critical}
          layout="full"
        />

        <Section
          tone="warning"
          title="Watch"
          subtitle="Schedule inspection in upcoming window"
          icon={Wrench}
          recs={grouped.warning}
          layout="full"
        />

        <Section
          tone="healthy"
          title="Healthy"
          subtitle="Operating within nominal parameters"
          icon={CheckCircle2}
          recs={grouped.healthy}
          layout="compact"
        />
      </div>
    </div>
  );
}

function Hero({
  counts,
}: {
  counts: Record<"critical" | "warning" | "healthy", number>;
}) {
  return (
    <div className="relative flex flex-col items-start gap-3 pt-2">
      <span className="font-mono text-[11px] tracking-[0.35em] text-violet-glow uppercase">
        Maintenance Recommendations
      </span>
      <h1 className="text-[28px] leading-tight font-semibold tracking-tight text-text">
        Action plans from the Maintenance Advisor
      </h1>
      <p className="max-w-2xl text-[13px] text-text-dim">
        Per-engine maintenance guidance generated by the Maintenance Advisor
        agent. Sorted by severity. Click any engine to inspect its sensors and
        degradation curve.
      </p>
      <div className="mt-2 flex items-center gap-2 font-mono text-[11px] text-text-faint">
        <span className="rounded-md border border-status-red/25 bg-status-red/10 px-2 py-0.5 text-status-red">
          {counts.critical} critical
        </span>
        <span className="rounded-md border border-status-amber/25 bg-status-amber/10 px-2 py-0.5 text-status-amber">
          {counts.warning} watch
        </span>
        <span className="rounded-md border border-status-green/25 bg-status-green/10 px-2 py-0.5 text-status-green">
          {counts.healthy} healthy
        </span>
      </div>
    </div>
  );
}

interface SectionProps {
  tone: Severity;
  title: string;
  subtitle: string;
  icon: React.ComponentType<{ className?: string }>;
  recs: Recommendation[];
  layout: "full" | "compact";
}

function Section({ tone, title, subtitle, icon: Icon, recs, layout }: SectionProps) {
  const tones = {
    critical: { text: "text-status-red", glow: "rgba(239,68,68,0.18)" },
    warning: { text: "text-status-amber", glow: "rgba(245,158,11,0.18)" },
    healthy: { text: "text-status-green", glow: "rgba(34,197,94,0.15)" },
  } as const;
  const t = tones[tone];

  if (recs.length === 0) return null;

  return (
    <section>
      <div className="mb-4 flex items-center gap-3">
        <div
          className={cn(
            "flex h-7 w-7 items-center justify-center rounded-md border bg-surface-2",
            tone === "critical" && "border-status-red/30",
            tone === "warning" && "border-status-amber/30",
            tone === "healthy" && "border-status-green/30",
          )}
        >
          <Icon className={cn("h-3.5 w-3.5", t.text)} />
        </div>
        <div className="flex flex-col leading-tight">
          <h2
            className={cn("text-[16px] font-semibold tracking-tight", t.text)}
            style={{ textShadow: `0 0 16px ${t.glow}` }}
          >
            {title}
          </h2>
          <span className="text-[11px] text-text-faint">{subtitle}</span>
        </div>
        <span className="ml-auto font-mono text-[11px] text-text-faint">
          {recs.length} engine{recs.length === 1 ? "" : "s"}
        </span>
      </div>

      {layout === "full" ? (
        <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
          {recs.map((r) => (
            <RecommendationCard key={r.engine_id} rec={r} />
          ))}
        </div>
      ) : (
        <div className="lift rounded-xl border border-border bg-surface/60 backdrop-blur-sm">
          {recs.map((r, i) => (
            <CompactRow key={r.engine_id} rec={r} divider={i < recs.length - 1} />
          ))}
        </div>
      )}
    </section>
  );
}

function RecommendationCard({ rec }: { rec: Recommendation }) {
  const tones = {
    critical: {
      border: "border-status-red/30",
      gradient: "from-status-red/10 to-transparent",
      ring: "shadow-[0_0_30px_-10px_rgba(239,68,68,0.4)]",
    },
    warning: {
      border: "border-status-amber/25",
      gradient: "from-status-amber/8 to-transparent",
      ring: "shadow-[0_0_30px_-10px_rgba(245,158,11,0.3)]",
    },
    healthy: {
      border: "border-border",
      gradient: "from-transparent to-transparent",
      ring: "",
    },
  } as const;
  const t = tones[rec.severity];

  return (
    <article
      className={cn(
        "lift relative flex flex-col gap-4 overflow-hidden rounded-xl border bg-gradient-to-br p-5 backdrop-blur-sm",
        t.border,
        t.gradient,
        t.ring,
      )}
    >
      <header className="flex items-start justify-between gap-3">
        <div className="flex items-center gap-3">
          <Link
            to={`/engine/${rec.engine_id}`}
            className="font-mono text-[22px] font-semibold tracking-tight text-text hover:text-violet-glow"
          >
            #{String(rec.engine_id).padStart(3, "0")}
          </Link>
          <SeverityBadge severity={rec.severity} />
        </div>
        <span className="font-mono text-[10px] text-text-faint">
          {rec.dataset} · Turbofan
        </span>
      </header>

      <div>
        <span className="inline-flex items-center rounded-md border border-violet/25 bg-violet/10 px-2 py-0.5 font-mono text-[10px] font-medium tracking-wider text-violet-glow uppercase">
          {rec.action_tag}
        </span>
        <p className="mt-2.5 text-[13px] leading-relaxed text-text">
          {rec.recommendation}
        </p>
      </div>

      <dl className="grid grid-cols-3 gap-2 border-t border-border pt-4">
        <Metric
          label="Time to critical"
          value={
            rec.severity === "critical"
              ? "Past"
              : `${rec.cycles_to_threshold}`
          }
          suffix={rec.severity === "critical" ? "threshold" : "cycles"}
          accent={rec.severity === "critical" ? "text-status-red" : undefined}
        />
        <Metric
          label="Current RUL"
          value={rec.predicted_rul.toFixed(0)}
          suffix="cycles"
        />
        <Metric
          label="Δ / cycle"
          value={rec.degradation_rate.toFixed(2)}
          accent={
            rec.degradation_rate < 0 ? "text-status-red" : "text-status-green"
          }
        />
      </dl>

      <div className="flex items-center gap-2">
        <Link
          to={`/engine/${rec.engine_id}`}
          className="flex flex-1 items-center justify-center gap-1.5 rounded-md border border-border bg-surface-2 px-3 py-2 text-[12px] font-medium text-text-dim transition-colors hover:border-border-strong hover:text-text"
        >
          <Eye className="h-3.5 w-3.5" />
          View Engine
          <ArrowUpRight className="h-3 w-3 opacity-60" />
        </Link>
        <button
          type="button"
          className="flex flex-1 items-center justify-center gap-1.5 rounded-md border border-violet/40 bg-gradient-to-b from-violet/25 to-violet/10 px-3 py-2 text-[12px] font-medium text-white shadow-[0_0_20px_rgba(168,85,247,0.2)] hover:from-violet/35 hover:to-violet/15"
        >
          <FileDown className="h-3.5 w-3.5" />
          Download PDF
        </button>
      </div>
    </article>
  );
}

function CompactRow({
  rec,
  divider,
}: {
  rec: Recommendation;
  divider: boolean;
}) {
  return (
    <div
      className={cn(
        "flex items-center gap-4 px-4 py-3",
        divider && "border-b border-border/60",
      )}
    >
      <Link
        to={`/engine/${rec.engine_id}`}
        className="font-mono text-[13px] text-text hover:text-violet-glow"
      >
        #{String(rec.engine_id).padStart(3, "0")}
      </Link>
      <SeverityBadge severity={rec.severity} />
      <span className="flex-1 text-[12px] text-text-dim">{rec.recommendation}</span>
      <span className="font-mono text-[11px] text-text-faint">
        {rec.predicted_rul.toFixed(0)} cycles
      </span>
      <Link
        to={`/engine/${rec.engine_id}`}
        className="rounded-md border border-border bg-surface-2 px-2.5 py-1 text-[11px] text-text-dim hover:border-border-strong hover:text-text"
      >
        View →
      </Link>
    </div>
  );
}

function Metric({
  label,
  value,
  suffix,
  accent,
}: {
  label: string;
  value: string;
  suffix?: string;
  accent?: string;
}) {
  return (
    <div className="flex flex-col">
      <span className="text-[10px] font-medium tracking-wider text-text-faint uppercase">
        {label}
      </span>
      <div className="mt-1 flex items-baseline gap-1">
        <span
          className={cn(
            "font-mono text-[16px] font-semibold tracking-tight",
            accent ?? "text-text",
          )}
        >
          {value}
        </span>
        {suffix && (
          <span className="text-[10px] text-text-faint">{suffix}</span>
        )}
      </div>
    </div>
  );
}
